### ISSUE TITLE
probe condition list

### ISSUE THREAD

**Issue by belledon** [CNCLgithub/mot#39]
as of now there are a total of 24 scenes with 12 conditions: batch (2) x probe (2) x tracker (3)
However, we will be splitting the 24 scenes along batch such that we can run 2 experiments of 12 trials with 6 (tracker x probe) 

You can find an early draft of render under `probe_stimuli/probes.tar.gz` and the probe map under `probe_stimuli/attention_analysis/exp0_probe_map.csv`.

The file name breaks down to `<scene>_<tracker>_t_<epoch>_[probe|noprobe]_[trg|dis].mp4`
## Tasks

- [x] Split the 24 scenes such that each batch of 12 is balanced across scene number (4 -> 118, something like every other).

- [x] For each batch create a condlist.json such that there are 6 conditions (tracker x probe). We are aiming for 120 trials per condition.  For each scene, there will be 10 repetitions (1 tracker x 5 time points x 2 target/distractor) per condition

- [ ] find a way to rotate each repetition to prevent memorization. One way is to change the render script but I would like to explore somehting on the psiturk side to see if its easy (otherwise we can change rendering) see [link]( https://www.encodedna.com/javascript/how-to-rotate-an-image-dynamically-using-javascript.htm). Note that the same rotations can be used across trackers and scenes (divide 2pi by 10) since each subject (condition) only sees one scene-tracker pair per scene. 

- [ ] add those box paths above to setup datasets
