### ISSUE TITLE
refactor TODO

### ISSUE THREAD

**Issue by eivinasbutkus** [CNCLgithub/mot#61]
- [x] small doc string for https://github.com/CNCLgithub/mot/blob/2a274043540b0532b4e1f6b004f82cb5fb8ed700/src/generative_models/data_generating_procedures/generate_dataset.jl#L49
- [x] clean up generate dataset scripts
- [x] look up in Gen automatic rejuvenation of unaddressed locations based on prior (dealing with desynchronization/low acceptance probability if just one address gets mh'ed)
